env:
  browser: true
  es6: true
extends:
  - plugin:vue/vue3-recommended
  - plugin:@typescript-eslint/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: vue-eslint-parser
parserOptions:
  ecmaVersion: 2018
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'
