env:
  browser: true
  es6: true
extends:
  - 'plugin:vue/vue3-recommended'
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'
rules: {
  'import/no-extraneous-dependencies': 'off',
  'vue/multi-word-component-names': 'off'
}
